global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telepush'  # see below

# telepush configuration here
receivers:
  - name: 'telepush'
    webhook_configs:
    - url: 'https://telepush.dev/api/inlets/alertmanager/f342d7'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']