version: '3'

services:
  prometheus:
    build: .
    ports:
      - 9000:9090
    links:
      - alertmanager:alertmanager
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - 3030:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
  # prometheus-bot:
  #         #container_name: telegrambot
  #   image: tienbm90/prometheus-bot:0.0.1

  #   volumes:
  #     - ./telegramBot/:/etc/telegramBot/
  #     - ./telegramBot/config.yaml:/config.yaml
  #     - ./telegramBot/template.tmpl:/etc/telegramBot/template.tmpl
  #   ports:
  #     - 9087:9087
  #   restart: always
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global
volumes:
  prometheus-data:
  grafana-data:
  telepush_data: