telegram_token: "5989686505:AAEoqeLCJJ1d3q5jdcrhJPj3he0B7TXEd4I"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "Asia/Tehran"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 4000
send_only: true # use bot only to send messages.